"use client";

import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { Layout } from "~/components/patterns/layout";
import Providers from "~/components/providers";
import { Suspense, useEffect } from "react";
import Script from "next/script";
import { useSession } from "next-auth/react";
import { redirect, usePathname } from "next/navigation";
import router from "next/router";
import SplashScreen from "~/components/patterns/splash-screen";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

// export const metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

const ProtectedRoutes = ({ children }: { children: React.ReactNode }) => {
  const { status } = useSession();
  const pathname = usePathname();

  useEffect(() => {
    const allowedUnauthenticatedPaths = ["/login", "/"];

    if (
      status !== "loading" &&
      status !== "authenticated" &&
      !allowedUnauthenticatedPaths.includes(pathname)
    ) {
      redirect("/login");
    }
  }, [status, pathname]);

  if (status === "loading") return <SplashScreen />;
  return <>{children}</>;
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Script
          src="https://app.lemonsqueezy.com/js/lemon.js"
          strategy="beforeInteractive"
        />
        <Suspense>
          <Providers>
            <ProtectedRoutes>
              <Layout>{children}</Layout>
            </ProtectedRoutes>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
